apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
  namespace: flask-app
type: Opaque
stringData:
  SECRET_KEY: "57d27fe43e260cc4083c7d77d"
  # Add other secrets here
  # REDIS_PASSWORD: "your-redis-password"